<style>
    .window-description .inputRow {
        margin-bottom: 10px;
    }
    .window-description .inputRow label {
        display: inline-block;
        vertical-align: middle;
        width: 142px;
    }
    .window-description .inputRow input, .window-description .inputRow textarea {
        display: inline-block;
        vertical-align: middle;
        margin-bottom: 0;
    }

    .window-description .inputRow input {
        width: 95%;
    }

    .window-description .inputRow textarea {
        width: 99%;
    }
</style>

<div class="inputRow">
    <label class="fieldlabel"><?php echo $this->user->lang("Name");?></label>
    <input class="required" type="text" name="name" value="<?php echo $this->name;?>" />
</div>
<div class="inputRow">
    <label class="fieldlabel"><?php echo $this->user->lang("Description");?></label>
    <input class="required" type="text" name="description" value="<?php echo $this->description;?>" />
</div>
<div class="inputRow">
    <label class="fieldlabel"><?php echo $this->user->lang("Details");?></label>
    <textarea name="detail" rows="15"><?php echo $this->detail; ?></textarea>
</div>
<div class="inputRow">
    <label class="fieldlabel"><?php echo $this->user->lang("Price");?></label>
    <input class="required" type="text" name="price" value="<?php echo $this->price;?>" />
</div>

<input type="hidden" name="id" value="<?php echo $this->id; ?>" />