<style type="text/css">
    .table2 tbody tr:nth-child(odd) td, .table2 tbody tr:nth-child(even) td {
        border-top: 0px;
        background-color: transparent;
    }
    tr.FreeDomainOptionsHeader, td.FreeDomainOptionsHeader {
        margin-bottom: 0px;
        padding-bottom: 0px;
    }
    .table2 tbody tr:nth-child(odd) td.FreeDomainOptionsHeaderBGC, .table2 tbody tr:nth-child(even) td.FreeDomainOptionsHeaderBGC {
        background-color: rgb(228, 228, 228);
    }
    tr.FreeDomainOptionsBody, td.FreeDomainOptionsBody {
        margin-top: 0px;
        padding-top: 0px;
    }
    .table2 tbody tr:nth-child(odd) td.FreeDomainOptionsBodyBGC, .table2 tbody tr:nth-child(even) td.FreeDomainOptionsBodyBGC {
        background-color: rgb(244, 244, 244);
    }
    .tableFreeDomain {
        margin-top: 8px;
        margin-bottom: 8px;
    }
    td.FirstRowWidth {
        width: 150px;
    }
    td.TLDRowWidth, select.TLDRowWidth {
        width: 147px;
    }
    label.FreeDomainOptionsLabel {
        text-align: left;
        font-weight: bold;
        margin-bottom: 10px;
        margin-top: -5px;
        font-size: 16px;
    }
    label.FreeDomainOptionsMargin, div.FreeDomainOptionsMargin {
        margin-left: 10px;
    }
    label.FreeDomainOptionsLabel2 {
        text-align:left;
        font-weight:bold;
    }
</style>

<script data-cfasync="false" type="text/javascript">
    $(document).ready(function() {
        $('.price').each(function() {
            $(this).keydown(function (e) {
                // Allow: delete, backspace, tab, escape, enter, . (110, 190)
                if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 ||
                    // Allow: Ctrl+A
                    (e.keyCode == 65 && e.ctrlKey === true) ||
                    // Allow: Ctrl+C
                    (e.keyCode == 67 && e.ctrlKey === true) ||
                     // Allow: Ctrl+V
                    (e.keyCode == 86 && e.ctrlKey === true) ||
                     // Allow: home, end, left, right
                    (e.keyCode >= 35 && e.keyCode <= 39)) {
                         // let it happen, don't do anything
                         return;
                }
                // Ensure that it is a number and stop the keypress
                if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
                    e.preventDefault();
                }
            });
        });
        clientexec.postpageload('#pricingtab');
    });

    function toggleFreeDomainFields(value, cycle){
        if (value == 0) {
            $('#freedomaindisplay'+cycle).hide();
        } else {
            $('#freedomaindisplay'+cycle).show();
        }
    }
</script>

<div class="fieldwrapper">
    <form id="pricingtab">
        <table class="table table-striped" width="100%">
            <thead>
            <tr>
                <td>
                    <table class="table2" width="100%">
                        <thead>
                        <tr class="FreeDomainOptionsHeader FreeDomainOptionsBody">
                            <td class="FreeDomainOptionsHeader FreeDomainOptionsBody FirstRowWidth">
                            </td>
                            <td class="FreeDomainOptionsHeader FreeDomainOptionsBody" width="65">
                                <label style="text-align:center;font-weight:bold;" class="fieldlabel"><?php echo $this->user->lang("Price");?></label>
                            </td>
                            <td class="FreeDomainOptionsHeader FreeDomainOptionsBody" width="65">
                                <label style="text-align:center;font-weight:bold;" class="fieldlabel"><?php echo $this->user->lang("Setup");?></label>
                            </td>
                            <td class="FreeDomainOptionsHeader FreeDomainOptionsBody" width="100">
                                <label style="text-align:center;font-weight:bold;" class="fieldlabel"><?php echo $this->user->lang("Allow in signup?");?></label>
                            </td>
                            <td class="FreeDomainOptionsHeader FreeDomainOptionsBody">
                                <?php if ($this->domain_product !== false) { ?>
                                <!-- THIS CELL IS TO DISPLAY THE FREE DOMAIN OPTIONS -->
                                <label class="fieldlabel FreeDomainOptionsLabel2"><?php echo $this->user->lang("Free Domain?");?></label>
                                <!-- /THIS CELL IS TO DISPLAY THE FREE DOMAIN OPTIONS -->
                                <?php } ?>
                            </td>
                        </tr>
                        </thead>
                    </table>
                </td>
            </tr>
            </thead>
            <tbody>

            <?php foreach ($this->priceExtraData as $cycle => $extraDataValues) {
                if ($cycle == 0) {
                    continue;
                } ?>

                <tr>
                    <td>
                        <table class="table2">
                            <tbody>
                            <tr>
                                <td class="FirstRowWidth">
                                    <?php echo $this->user->lang($this->priceExtraData[$cycle]['price_name']);?>
                                </td>
                                <td width="65">
                                    <input class="price" type="text" value="<?php echo $this->priceExtraData[$cycle]['price'];?>" name="price<?php echo $cycle; ?>" style="width:50px;"/>
                                </td>
                                <td width="65">
                                    <input class="price" type="text" value="<?php echo $this->priceExtraData[$cycle]['setup'];?>" name="setup<?php echo $cycle; ?>" style="width:50px;"/>
                                </td>
                                <td width="100" style="text-align:center;">
                                    <input type="checkbox" name="price<?php echo $cycle; ?>_checked" value="1" <?php if ($this->priceExtraData[$cycle]['price_checked'] == 1) echo "checked";?> />
                                </td>
                                <td>
                                    <?php if ($this->domain_product !== false) { ?>
                                    <!-- THIS CELL IS TO DISPLAY THE FREE DOMAIN OPTIONS -->
                                    <span data-toggle="tooltip" title='<?php echo $this->user->lang("* Select \"One-Time\" for the domain to be free only the first billing period.\n* Select \"Recurring\" for the domain to be free on every billing period.");?>'>
                                        <select name="freedomain<?php echo $cycle; ?>" style="width: 100px;" onchange="toggleFreeDomainFields(this.value, '<?php echo $cycle; ?>')">
                                            <option <?php echo ($this->priceExtraData[$cycle]['freedomain'] == 0)? "selected" : ""; ?> value="0"><?php echo $this->user->lang("None");?></option>
                                            <option <?php echo ($this->priceExtraData[$cycle]['freedomain'] == 1)? "selected" : ""; ?> value="1"><?php echo $this->user->lang("One-Time");?></option>
                                            <option <?php echo ($this->priceExtraData[$cycle]['freedomain'] == 2)? "selected" : ""; ?> value="2"><?php echo $this->user->lang("Recurring");?></option>
                                        </select>
                                    </span>
                                    <!-- THIS CELL IS TO DISPLAY THE FREE DOMAIN OPTIONS -->
                                    <?php } ?>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                        <?php if ($this->domain_product !== false) { ?>
                        <!-- THESE CELLS ARE TO DISPLAY THE FREE DOMAIN CONFIGURATION -->
                        <table class="table2 tableFreeDomain" id="freedomaindisplay<?php echo $cycle; ?>" style="display: <?php echo $this->priceExtraData[$cycle]['freedomaindisplay']; ?>">
                            <tbody>
                            <tr class="FreeDomainOptionsHeader">
                                <td class="FreeDomainOptionsHeader FirstRowWidth">
                                </td>
                                <td colspan="2" class="FreeDomainOptionsHeader FreeDomainOptionsHeaderBGC">
                                    <label class="fieldlabel FreeDomainOptionsLabel FreeDomainOptionsMargin"><?php echo $this->user->lang("Free Domain Options");?></label>
                                </td>
                            </tr>
                            <tr class="FreeDomainOptionsBody">
                                <td class="FirstRowWidth FreeDomainOptionsBody">
                                </td>
                                <td class="FreeDomainOptionsBody FreeDomainOptionsBodyBGC TLDRowWidth">
                                    <label class="fieldlabel FreeDomainOptionsMargin FreeDomainOptionsLabel2"><?php echo $this->user->lang("TLD");?></label>
                                    <div class="FreeDomainOptionsMargin">
                                        <select multiple="multiple" placeholder="Select tld(s)" class="TLDRowWidth" name="domain_extension<?php echo $cycle; ?>[]">
                                            <?php foreach($this->packages as $package) {
                                                $selected = (is_array($this->priceExtraData[$cycle]['domain_extension']) && in_array($package['id'], $this->priceExtraData[$cycle]['domain_extension'])) ? "selected" : "";?>
                                                <option <?php echo $selected; ?> value="<?php echo $package['id'];?>"><?php echo $package['planname'];?></option>
                                            <?php } ?>
                                        </select>
                                    </div>
                                </td>
                                <td class="FreeDomainOptionsBody FreeDomainOptionsBodyBGC">
                                    <label class="fieldlabel FreeDomainOptionsLabel2"><?php echo $this->user->lang("Domain Billing Cycle");?></label>
                                    <select multiple="multiple" placeholder="Select billing cycle(s)" style="width: 473px;" name="domain_cycle<?php echo $cycle; ?>[]">
                                        <?php foreach ($this->periods as $periods) {
                                            $selected = (is_array($this->priceExtraData[$cycle]['domain_cycle']) && in_array($periods['period'], $this->priceExtraData[$cycle]['domain_cycle'])) ? "selected" : "";?>
                                            <option <?php echo $selected; ?> value="<?php echo $periods['period'];?>" > <?php echo $periods['name'];?> </option>
                                        <?php } ?>
                                    </select>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                        <!-- /THESE CELLS ARE TO DISPLAY THE FREE DOMAIN CONFIGURATION -->
                        <?php } ?>
                    </td>
                </tr>
            <?php } ?>

            <tr>
                <td>
                    <table class="table2">
                        <tbody>
                        <tr>
                            <td class="FirstRowWidth">
                                <?php echo $this->user->lang($this->priceExtraData[0]['price_name']);?>
                            </td>
                            <td width="146">
                                <input class="price" type="text" value="<?php echo $this->priceExtraData[0]['price'];?>" name="price0" style="width:50px;"/>
                            </td>
                            <td width="100" style="text-align:center;">
                                <input type="checkbox" name="price0_checked" value="1" <?php if ($this->priceExtraData[0]['price_checked'] == 1) echo "checked";?> />
                            </td>
                            <td>
                                <?php if ($this->domain_product !== false) { ?>
                                <!-- THIS CELL IS TO DISPLAY THE FREE DOMAIN OPTIONS -->
                                <span data-toggle="tooltip" title='<?php echo $this->user->lang("* Select \"One-Time\" for the domain to be free only the first billing period.\n* Select \"Recurring\" for the domain to be free on every billing period.");?>'>
                                    <select name="freedomain0" style="width: 100px;" onchange="toggleFreeDomainFields(this.value, '0')">
                                        <option <?php echo ($this->priceExtraData[0]['freedomain'] == 0)? "selected" : ""; ?> value="0"><?php echo $this->user->lang("None");?></option>
                                        <option <?php echo ($this->priceExtraData[0]['freedomain'] == 1)? "selected" : ""; ?> value="1"><?php echo $this->user->lang("One-Time");?></option>
                                        <option <?php echo ($this->priceExtraData[0]['freedomain'] == 2)? "selected" : ""; ?> value="2"><?php echo $this->user->lang("Recurring");?></option>
                                    </select>
                                </span>
                                <!-- THIS CELL IS TO DISPLAY THE FREE DOMAIN OPTIONS -->
                                <?php } ?>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                    <?php if ($this->domain_product !== false) { ?>
                    <!-- THESE CELLS ARE TO DISPLAY THE FREE DOMAIN CONFIGURATION -->
                    <table class="table2 tableFreeDomain" id="freedomaindisplay0" style="display: <?php echo $this->priceExtraData[0]['freedomaindisplay']; ?>">
                        <tbody>
                        <tr class="FreeDomainOptionsHeader">
                            <td class="FreeDomainOptionsHeader FirstRowWidth">
                            </td>
                            <td colspan="2" class="FreeDomainOptionsHeader FreeDomainOptionsHeaderBGC">
                                <label class="fieldlabel FreeDomainOptionsLabel FreeDomainOptionsMargin"><?php echo $this->user->lang("Free Domain Options");?></label>
                            </td>
                        </tr>
                        <tr class="FreeDomainOptionsBody">
                            <td class="FirstRowWidth FreeDomainOptionsBody">
                            </td>
                            <td class="FreeDomainOptionsBody FreeDomainOptionsBodyBGC TLDRowWidth">
                                <label class="fieldlabel FreeDomainOptionsMargin FreeDomainOptionsLabel2"><?php echo $this->user->lang("TLD");?></label>
                                <div class="FreeDomainOptionsMargin">
                                    <select multiple="multiple" placeholder="Select tld(s)" class="TLDRowWidth" name="domain_extension0[]">
                                        <?php foreach($this->packages as $package) {
                                            $selected = (is_array($this->priceExtraData[0]['domain_extension']) && in_array($package['id'], $this->priceExtraData[0]['domain_extension'])) ? "selected" : "";?>
                                            <option <?php echo $selected; ?> value="<?php echo $package['id'];?>"><?php echo $package['planname'];?></option>
                                        <?php } ?>
                                    </select>
                                </div>
                            </td>
                            <td class="FreeDomainOptionsBody FreeDomainOptionsBodyBGC">
                                <label class="fieldlabel FreeDomainOptionsLabel2"><?php echo $this->user->lang("Domain Billing Cycle");?></label>
                                <select multiple="multiple" placeholder="Select billing cycle(s)" style="width: 473px;" name="domain_cycle0[]">
                                    <?php foreach ($this->periods as $periods) {
                                        $selected = (is_array($this->priceExtraData[0]['domain_cycle']) && in_array($periods['period'], $this->priceExtraData[0]['domain_cycle'])) ? "selected" : "";?>
                                        <option <?php echo $selected; ?> value="<?php echo $periods['period'];?>" > <?php echo $periods['name'];?> </option>
                                    <?php } ?>
                                </select>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                    <!-- /THESE CELLS ARE TO DISPLAY THE FREE DOMAIN CONFIGURATION -->
                    <?php } ?>
                </td>
            </tr>

            <tr>
                <td>
                    <table class="table2">
                        <tbody>
                        <tr>
                            <td class="FirstRowWidth">
                                <?php echo $this->user->lang("Late Fee");?>
                            </td>
                            <td>
                                <input class="price" type="text" value="<?php echo $this->latefee;?>" name="latefee" style="width:50px;"/>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
            <tr>
                <td>
                    <table class="table2">
                        <tbody>
                        <tr>
                            <td>
                                <label class="checkbox inline"><input type="checkbox" name="taxable" value="1" <?php if ($this->taxable == 1) echo "checked";?> /><?php echo $this->user->lang("Product is Taxable?");?></label>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
            <tr>
                <td>
                    <table class="table2">
                        <tbody>
                        <tr>
                            <td class="FirstRowWidth">
                                <label class="fieldlabel"><span class='tip-target' data-toggle="tooltip"  data-placement="top" title='Select the day you want to prorate all new orders to.'><?php echo $this->user->lang("Prorate To Day");?></span></label>
                            </td>
                            <td>
                                <span class='tip-target' data-toggle="tooltip" data-placement='top' title="<?php echo $this->user->lang('<b>Prorate To Day</b> and <b>Include Following Payment</b> should be used only for Billing Cycles which have their Time Unit in Months or Years.'); ?>">
                                    <select name="prorateToDay" style="width: 214px;">
                                        <option <?php echo ($this->prorateToDay == 0)? "selected" : ""; ?> value="0"><?php echo $this->user->lang("Do Not Pro-Rate");?></option>
                                        <?php for ($prorateDay = 1; $prorateDay <= 28; $prorateDay++) { ?>
                                            <option <?php echo ($this->prorateToDay == $prorateDay)? "selected" : ""; ?> value="<?php echo $prorateDay; ?>"><?php echo $prorateDay; ?></option>
                                        <?php } ?>
                                    </select>
                                </span>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
            <tr>
                <td>
                    <table class="table2">
                        <tbody>
                        <tr>
                            <td class="FirstRowWidth">
                                <label class="fieldlabel"><span class='tip-target' data-toggle="tooltip"  data-placement="top" title='Select if you want to include the next payment when prorating.'><?php echo $this->user->lang("Include Following Payment");?></span></label>
                            </td>
                            <td>
                                <?php if ($this->includeFollowingPayment === null) { $this->includeFollowingPayment = -1; } ?>
                                <span class='tip-target' data-toggle="tooltip" data-placement='top' title="<?php echo $this->user->lang('<b>Prorate To Day</b> and <b>Include Following Payment</b> should be used only for Billing Cycles which have their Time Unit in Months or Years.'); ?>">
                                    <select name="includeFollowingPayment" style="width: 214px;" >
                                        <option <?php echo ($this->includeFollowingPayment == -1)? "selected" : ""; ?> value="-1"><?php echo $this->user->lang("Never");?></option>
                                        <option <?php echo ($this->includeFollowingPayment == 0)? "selected" : ""; ?> value="0" ><?php echo $this->user->lang("If prorating 10 days or less");?></option>
                                        <option <?php echo ($this->includeFollowingPayment == 2)? "selected" : ""; ?> value="2" ><?php echo $this->user->lang("Always except for monthly payments");?></option>

                                        <!--
                                            This option was added to allow using paypal subscriptions on other than monthly payments.
                                            Without it, for quarterly, semianual and annual payments, if there's prorating and inclusion of the following payment, paypal's subscription
                                            initial trial period would exceed 90 days, so a subscription can't be established.
                                        -->
                                        <option <?php echo ($this->includeFollowingPayment == 3)? "selected" : ""; ?> value="3" ><?php echo $this->user->lang("Only for monthly payments");?></option>

                                        <option <?php echo ($this->includeFollowingPayment == 1)? "selected" : ""; ?> value="1" ><?php echo $this->user->lang("Always");?></option>
                                    </select>
                                </span>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
            <tr>
                <td>
                    <table class="table2">
                        <tbody>
                        <tr>
                            <td class="FirstRowWidth">
                                <label class="fieldlabel"><span class='tip-target' data-toggle="tooltip"  data-placement="top" title='Enter an existing Coupon Code to have the coupon automatically applied during checkout.'><?php echo $this->user->lang("Automatic Coupon");?></span></label>
                            </td>
                            <td>
                                <input type="text" name="automaticCoupon" value="<?php echo $this->automaticCoupon;?>" style="width:200px;"/>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
            </tbody>
            <tfoot>
            <tr>
                <td>
                    <div class="alert alert-block">
                        <ul>
                            <li><?php echo $this->user->lang("Addon prices for billing cycles not used in this product will not be available to the client, unless you select the force show option in the addon setup screen.");?></li>
                            <li><?php echo $this->user->lang("<b>Prorate To Day</b> and <b>Include Following Payment</b> will also apply to the addons purchased with the product.");?></li>
                            <li><?php echo $this->user->lang("<b>Prorate To Day</b> and <b>Include Following Payment</b> should be used only for Billing Cycles which have their Time Unit in Months or Years.");?></li>
                        </ul>
                    </div>
                    <div class="form-actions">
                        <div class="pull-right">
                          <button type="submit" class="submit-pricing btn btn-primary"><?php echo $this->user->lang("Save Changes");?></button>
                        </div>
                    </div>
                </td>
            </tr>
            </tfoot>
        </table>
    </form>
</div>