<?php
    if ($this->from == 'signup') {
        $containerClass = 'col-12';
    } else if ($this->from == 'invoice') {
        $containerClass = 'col-12';
    } elseif ($this->from == 'paymentmethod') {
        $containerClass = 'col-12';
    }
?>

<input type="hidden" id="squarepaymentCardNonce" name="squarepayment_plugincustomfields[squarepaymentCardNonce]" value="">

<div class="<?php echo $containerClass; ?>">

    <script type="text/javascript" src="<?php echo $this->SqPaymentFormLibrary; ?>"></script>
    <link rel="stylesheet" type="text/css" href="plugins/gateways/squarepayment/mysqpaymentform.css">
    <div class="row" id="form-container">
        <div class="col-md-12">
            <div class="form-elem">
                <div id="sq-card-number"></div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-elem">
                <div id="sq-expiration-date"></div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-elem">
                <div id="sq-cvv"></div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-elem">
                <div id="sq-postal-code"></div>
            </div>
        </div>
    </div>
</div>
<div class="text-right col-12">
<?php if ($this->from == 'signup') { ?>
    <a style="margin-left:0px;cursor:pointer;" class="app-btns primary customButton pull-left center-on-mobile squarepaymentButton" id="customButton"></a>
<?php } elseif ($this->from == 'invoice') { ?>
    <button class="app-btns primary squarepaymentButton"><?php echo $this->user->lang('Pay Invoice'); ?></button>
<?php } elseif ($this->from == 'paymentmethod') { ?>
    <button style="margin-left:0px;cursor:pointer;" class="btn btn-primary customButton squarepaymentButton pull-left" id="customButton"><?php echo $this->user->lang('Update Credit Card'); ?></button>
<?php } ?>
</div>

<script type="text/javascript">
    // Create and initialize a payment form object
    const paymentForm = new SqPaymentForm(
        {
            // Initialize the payment form elements
            applicationId: '<?php echo $this->applicationid; ?>',
            inputClass:    'sq-input',
            autoBuild:     false,
            // Customize the CSS for SqPaymentForm iframe elements
            inputStyles: [
                {
                    fontSize:         '16px',
                    lineHeight:       '24px',
                    padding:          '16px',
                    placeholderColor: '#a0a0a0',
                    backgroundColor:  'transparent',
                }
            ],
            // Initialize the credit card placeholders
            cardNumber: {
                elementId:   'sq-card-number',
                placeholder: 'Card Number'
            },
            cvv: {
                elementId:   'sq-cvv',
                placeholder: 'CVV'
            },
            expirationDate: {
                elementId:   'sq-expiration-date',
                placeholder: 'MM/YY'
            },
            postalCode: {
                elementId:   'sq-postal-code',
                placeholder: 'Postal'
            },
            // SqPaymentForm callback functions
            callbacks: {
                /*
                * callback function: cardNonceResponseReceived
                * Triggered when: SqPaymentForm completes a card nonce request
                */
                cardNonceResponseReceived: function (errors, nonce, cardData) {
                    if (errors) {
                        // Log errors from nonce generation to the browser developer console.
                        console.error('Encountered errors:');

                        errors.forEach(function (error) {
                            console.error('  ' + error.message);
                        });

                        alert('Encountered errors, check browser developer console for more details');
                        return;
                    }

                    var elem = document.getElementById("squarepaymentCardNonce");
                    elem.value = nonce;

                    <?php if ($this->from == 'invoice' || $this->from == 'signup') { ?>
                        $('#submitButton').click();
                    <?php } elseif ($this->from == 'paymentmethod') { ?>
                        var valid = $('.update-payment-method-frm').parsley('validate');
                        if (valid) $('.update-payment-method-frm').submit();
                    <?php } ?>
                },

                paymentFormLoaded: function() {
                    paymentForm.setPostalCode('<?php echo $this->userZipcode;?>');
                }
            }
        }
    );

    $('.squarepaymentButton').on('click', function(e) {
        <?php if ($this->from == 'signup') { ?>
            if ($('.squarepaymentButton').hasClass('disabled')) {
                return;
            }

            var password_validated = true;

            <?php if (!$this->loggedIn) { ?>
                $('.parsley-error-list.help-block').parent().removeClass('has-error');
                $('.parsley-error-list.help-block').remove();
                e.preventDefault();

                //let's validate remote data
                if ($('#password').length > 0) {
                    if ($.trim($('#password').val()) == "") return;
                    $.ajax({
                        type: "POST",
                        data: {"password": $('#password').val()},
                        url: 'index.php?controller=signup&fuse=admin&action=testpasswordstrength',
                        async: false,
                        success : function(response) {
                            json = clientexec.parseResponse(response);
                            if (!json.valid) {
                                password_validated = false;
                                $('#password').parent().addClass('has-error');
                                $('#password').after('<span class="help-block parsley-error-list">'+json.errorMessage+'</span>');
                                $('#password').get(0).scrollIntoView();
                            }
                        }
                    });
                }
            <?php } ?>

            if (password_validated && $('#submitForm').parsley('validate')) {
        <?php } ?>

        <?php if ($this->from == 'signup') { ?>
            }
        <?php } ?>

        // Don't submit the form until SqPaymentForm returns with a nonce
        e.preventDefault();

        // Request a nonce from the SqPaymentForm object
        paymentForm.requestCardNonce();
    });

    var paymentFormBuilt = false;

    $('.squarepaymentpaymentbutton, .squarepaymentPaymentInformation').on('paymentShow', function(e) {
        if (!paymentFormBuilt) {
            paymentForm.build();
            paymentFormBuilt = true;
        }
    });
</script>